.header on
.mode column

CREATE TABLE TB_PROFESSOR (
  PROFESSOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_PROFESSOR TEXT NOT NULL,
  DATA_NASC_PROF TEXT NOT NULL
);

CREATE TABLE TB_ALUNO (
  ALUNO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_ALUNO TEXT NOT NULL,
  DATA_NASC_ALUNO TEXT NOT NULL
);

CREATE TABLE TB_DISCIPLINA (
  DISCIPLINA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME_DISCIPLINA TEXT NOT NULL
);

CREATE TABLE TB_MATRICULA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DATA_MATRICULA TEXT NOT NULL,
  ALUNO_ID INTEGER NOT NULL,
  DISCIPLINA_ID NOT NULL,
  PROFESSOR_ID NOT NULL,
  FOREIGN KEY (ALUNO_ID)
    REFERENCES TB_ALUNO (ALUNO_ID),
  FOREIGN KEY (DISCIPLINA_ID)
    REFERENCES TB_DISCIPLINA (DISCIPLINA_ID),
  FOREIGN KEY (PROFESSOR_ID)
    REFERENCES TB_PROFESSOR (PROFESSOR_ID)
);
  
INSERT INTO TB_PROFESSOR (NOME_PROFESSOR, DATA_NASC_PROF)
VALUES('Ricardo Duarte Taveira', '09/06/1999');

INSERT INTO TB_ALUNO (NOME_ALUNO, DATA_NASC_ALUNO)
VALUES('Maria Lara Silva de Agreela', '10/04/2007');

INSERT INTO TB_DISCIPLINA (NOME_DISCIPLINA)
VALUES('Banco de Dados');

INSERT INTO TB_MATRICULA (ALUNO_ID, DISCIPLINA_ID, DATA_MATRICULA, PROFESSOR_ID)
  VALUES (1, 1, '24/03/2023', 1);

.print
.print 'TABELA PROFESSORES'
SELECT * FROM TB_PROFESSOR;

.print
.print 'TABELA ALUNOS'
SELECT * FROM TB_ALUNO;

.print
.print 'TABELA DISCIPLINAS'
SELECT * FROM TB_DISCIPLINA;

.print
.print 'TABELA MATRICULA'
  SELECT * FROM TB_MATRICULA;
