-- CRIANDO UMA TABELA: CREATE
CREATE TABLE IF NOT EXISTS PRODUTOS (COD TEXT, NOME TEXT, VALOR REAL);
-- LENDO UMA TABELA: READ
SELECT * FROM PRODUTOS;
-- ATUALIZANDO UMA TABELA: UPDATE
INSERT INTO PRODUTOS (COD, NOME, VALOR) VALUES ("12325", "Borracha", 0.50), ("12326", "Lápis", 0.50), ("12327", "Caneta", 0.50), ("12328", "Caderno", 40.00), ("12328", "Régua", 3.00);
UPDATE PRODUTOS SET VALOR = 1.00 WHERE COD = "12327";
-- DELETANDO UM VALOR DA TABELA: DELETE
DELETE FROM PRODUTOS WHERE COD = "12325";

-- MOSTRANDO A TABELA NO TERMINAL
SELECT * FROM PRODUTOS;
